lint: Fixes the lint job
flake8 released version 5.0.0. Because of this, pyproject-flake8
is failing because a class it was using from flake8 no longer exists,
resulting in the following error:

AttributeError: module 'flake8.options.config' has no attribute 'ConfigFileFinder'

This commit can be reversed once this issue is resolved:
https://github.com/csachs/pyproject-flake8/issues/13